title: "Il Mio toposito - topolini.cc"
background: 
  blur: 5 # Effetto sfocato figo se vuoi che il testo si legga bene
layout:
  header:
    showGreeting: true
    greeting: "Ciao, sono Pupi e questo Ã¨ il mio toposito"
